recettes = {
    "purpose": "get recipe from database",
    "licence": "ODbL 2.0",
    "format": "json",
    "type": "FeatureCollection",
    "version": "draft",
    "code": "jjdHpajappalmnrkrmiapksmcmcaenpnajkDDno56456wv466V6a6e8vYY46aRV6Arv6reth6h46shOP4s6h4a66",
    "recipes": {
        "1": {
            "key": "1",
            "title": "Gâteau au chocolat mi-cuit",
            "description": "Préchauffer le four à 200°C. Faire fondre 250g de chocolat noir 60-70% au bain marie, baisser le feu et ajouter 250g de beurre doux pommade. Bien mélanger et verser le mélange qui doit etre liquide dans un saladier dans lequel on ajoute 250g de sucre et 70g de farine blanche en mélangeant énergétiquement. L'appareil doit être fluide, si ce n'est pas le cas rajouter de l'eau, puis ajouter les 4 oeufs battus en omelette. On doit obtenir une texture entre fluide et compacte. Enfourner le gâteau à 150°C 25 min. Laisser le gâteau refroidir dans son moule 10 min et démouler.",
            "source": "Suzy Palatin",
            "source_type": "Texte",
            "ingredients": [
                "sucre",
                "oeuf",
                "farine",
                "chocolat",
                "beurre"
            ],
            "astuces": "Si on a pas de chocolat 60-70% de chocolat noir alors baisser le taux de sucre et de beurre. On pourra le mettre en mode grill 3 minutes pour une belle croute.",
            "commentaire": "Recette testée et approuvée !",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette de saison"
        },
        "2": {
            "key": "2",
            "title": "Lentille aux légumes étouffés",
            "description": "Faire tremper les lentilles blondes (environ 300g) dans de l'eau froide. Dans une casserole mettre à ébullition 50 cl d'eau et y ajouter un peu de laurier et de sauge hors du feu. Emincer et réserver dans des bols séparés, un oignon rouge, 2 échalottes, deux tiges de fenouil (partie verte tubulée), un poivron et 3 gousses d'ail. Découper une bonne moitié de courgette jaune en dés à laquelle on rajoute un peu de sel et de sauce nuoc mam et sauce soja. Faire revenir le fenouil et les oignons rouges à la poêle, puis rajouter les échalottes, l'ail et les courgettes, recouvrir des lentilles égouttées. L'idée de cuire à l'étouffée à 120°C environ, les lentilles doivent opérer comme une couche qui va cuire avec les vapeurs d'eau des légumes, rajouter un peu d'eau infusée au fur et à mesure de la cuisson, cuire à découvert. Quand toute l'eau s'est évaporée, les lentilles devraient être prêtes !",
            "source": "Cuistot Dingo",
            "source_type": "Texte",
            "ingredients": [
                "lentille blonde",
                "fenouil",
                "oignon rouge",
                "echalote",
                "ail",
                "courgette",
                "sauce soja",
                "sauge"
            ],
            "astuces": "",
            "commentaire": "Recette testée et approuvée !",
            "Nombre de personnes": "6",
            "type": "plat",
            "saison": "Recette pas de saison : fenouil,ail,courgette"
        },
        "3": {
            "key": "3",
            "title": "Macarrons",
            "description": "Sortir en avance 150g de beurre qu'on coupera en petits cubes (pour qu'il devienne pommade). Dans un robot, mixer 275g de poudre d'amande et 250g de sucre glace, tamiser. Fouetter 6 blancs d'oeufs et une fois bien les oeufs bien mousseux, ajouter 70g de sucre semoule, continuer de fouetter, ajouter 70g de sucre semoule et fouetter encore 1 min, ajouter le sucre restant (70g) et fouetter encore une minute jusqu'à avoir un bec d'oiseau et un blanc bien lisse. A l'aide d'une maryse, incorporé délicatement aux blancs, le mélange amande et sucre glace tamisé. Ajouter alors un demi blanc d'oeuf préalablement battu pour faire retomber légèrement la pâte et qu'elle se ramollisse à peine. Sur un plaque allant au four, coiffée de papier sulfurisé, coucher à l'aide de la poche à douille des macarons de 3 à 4 cm de diamètre. Tapoter légèrement la plaque pour que les macarons se tassent un peu et parsemer d'amandes hachées(100g). Préchauffer le four à 150°C. Laisser les macarons 10 min de repos à l'air libre, et enfourner 15 min jusqu'à ce qu'ils croûtent légèrement. Une fois sortis, faire perler de l'eau entre la plaque et le papier à chaque coin pour que la vapeur d'eau aide au décollement des macarons lorsqu'ils seront froid. Mélanger 320g de pâte d'amande 65% et 120g de pulpe d'amande non sucrée, ajouter 8cl de crème liquide et 150g de beurre pommade coupés en dés. Fouetter énergiquement pour bien émulsionner l'ensemble. Avec une poche garnir les coques de crème d'amande. Laisser les macarons s'affiner 12h au frigo.",
            "source": "La Durée - Sucré",
            "source_type": "Texte",
            "ingredients": [
                "oeuf",
                "sucre glace",
                "sucre",
                "amande",
                "pate d'amande",
                "pulpe d'amande",
                "beurre",
                "creme liquide"
            ],
            "astuces": "",
            "commentaire": "",
            "Nombre de personnes": "6",
            "type": "plat",
            "saison": "Recette de saison"
        },
        "4": {
            "key": "4",
            "title": "Champignon Wellington",
            "description": "Découper les pieds trop durs des shiitakes (500g)  et les émincer en lamelles. Les faire revenir dans une poêle avec 20 grammes de beurre. Finir la cuisson en déglaçant à la sauce soja (1 cac). Les réserver pour qu’ils refroidissent complètement. Prendre la moitié des champignons bruns (400g), les brosser, les découper en quartiers et les faire revenir dans une poêle avec 20 grammes de beurre. Les flamber au cognac (1 bouchon facultatif) et finir la cuisson en ajoutant les noisettes (grosse poignée), du sel et du poivre. Les réserver pour qu’ils refroidissent complètement. Prendre la seconde moitié des champignons bruns (400g), les brosser et les émincer finement. Émincer les échalotes (2 grosses) et faire revenir le tout dans une poêle avec 20 grammes de beurre. Assaisonner généreusement et les réserver pour qu’ils refroidissent complètement. Profiter de la poêle encore chaude pour faire toaster les deux tranches de pain de mie. Étaler la pâte feuilletée pour obtenir un rectangle d’environ 45 par 30 centimètres. Garnir au centre avec la moitié des champignons bruns émincés, puis des shiitake par-dessus. Ajouter les tranches de pain de mie, les champignons en quartiers et finir avec la fin de ceux émincés. Tenter de former un rectangle le plus compact et propre possible. Plier le bas de la pâte feuilletée par-dessus les champignons, brosser le dessus à l’œuf battu et replier le haut de la pâte par-dessus. Replier les bordures sous votre construction pour obtenir un rectangle bien fermé et bien serré. À l’aide d’un couteau d’office, dessiner les motifs de votre choix sur votre création. Brosser à l’œuf battu, saupoudrer de cristaux de sel et enfourner 45 minutes dans un four préchauffé à 180 °C. Découper avec un couteau à dents et servir bien chaud.",
            "source": "Journal Le Monde",
            "source_type": "Texte",
            "ingredients": [
                "oeuf",
                "champignon brun",
                "shiitake",
                "pate feuilletee",
                "echalote",
                "noisette",
                "beurre",
                "sauce soja",
                "pain de mie"
            ],
            "astuces": "Bien serré la pâte feuilletée.",
            "commentaire": "Excellent pour un plat de fêtes.",
            "Nombre de personnes": "6",
            "type": "plat",
            "saison": "Recette pas de saison : noisette"
        },
        "5": {
            "key": "5",
            "title": "Crêpe comme on les aime",
            "description": "Poêler le celeri branche finement coupé. Rajouter 1 c.a.c. de miso, des allumettes de chorizo, les champignons escalopés, déglacer à l'eau et couvrir créer une ambiance humide. En fin de cuisson ajouter une noix de gorgonzola. Huiler une deuxième poêle et dorer la crêpe, y mettre l'oeuf, avec un écrasé de persil et graines de coriandre (au mortier). Ajouter fromage rapé, le mélange celerie champignons, du fromage à raclette et le tour est joué !",
            "source": "Cuistot Dingo",
            "source_type": "Texte",
            "ingredients": [
                "oeuf",
                "champignon brun",
                "crepe",
                "celeri branche",
                "miso",
                "graine de coriandre",
                "persil",
                "gruyere",
                "fromage a raclette",
                "chorizo"
            ],
            "astuces": "Veiller à bien dorer la crêpe et à faire attention à ce qu'elle n'accroche pas trop. Les champignons coupés en gros donnent du volume",
            "commentaire": "Excellent.",
            "Nombre de personnes": "",
            "type": "plat",
            "saison": "Recette pas de saison : celeri branche"
        },
        "6": {
            "key": "6",
            "title": "Pizza miam miam",
            "description": "Mixer 50g de yaourt soja avec artichaut en boîte, sauter les champignons. Sur la pâte à pizza, mettre le coulis de yaourt artichaut, le jambon blanc en parcelle, la mozzarella di buffala (300g), les champignons, le gouda. Arroser d'huile en fin de cuisson.",
            "source": "Cuistot Muka Dingo",
            "source_type": "Texte",
            "ingredients": [
                "pate a pizza",
                "champignon brun",
                "artichaut",
                "yaourt soja",
                "gouda",
                "mozzarella"
            ],
            "astuces": "",
            "commentaire": "La creme d'artichaut donne un côté crémeux, excellent.",
            "Nombre de personnes": "2",
            "type": "plat",
            "saison": "Recette pas de saison : artichaut"
        },
        "7": {
            "key": "7",
            "title": "Haricot oeil noir coriandre coco",
            "description": "Tremper les haricots, la veille. Les cuire au lait de coco. Cuire les carottes escalopées grossièrement. A mi cuisson, rajouter une c.a.c de miso aux haricots, et un peu d'eau si le lait de coco s'est évaporée. On cherche à avoir une bonne quantité de bouillon. Préparer la mixture, graines de coriandre et persil haché, l'écraser au mortier en exhumer les saveurs, le rajouter au bouillon.",
            "source": "Inconnue",
            "source_type": "Texte",
            "ingredients": [
                "persil",
                "miso",
                "lait de coco",
                "haricot oeil noir",
                "coriandre"
            ],
            "astuces": "",
            "commentaire": "",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette de saison"
        },
        "8": {
            "key": "8",
            "title": "biscuits énergie",
            "description": "Préparer la pâte en mélangeant 150g de farine d'épeautre, 100g de farine de kamut, 115g d'huile d'olive et 15g d'eau. Pétrir en serrant le poing, et que la pâte ressorte entre les doigts. Laisser la pâte au frigo 30 min. La sortir et l'émietter du bout des doigts, y ajouter les graines, les amandes, les noix, les noisettes. Pour la quantité environ moitié du poids de la pâte. Dans un robot mixeur commencer à mixer  Pendant ce temps, dans un petit verre, mettre 1/3 de chocolat blanc et venir mouiller avec du lait d'amande jusque la moitié, et le mettre 40 secondes au micro ondes. Mélanger et verser en filet dans le robot pendant le mélange pour amalgamer les éléments. Façonner des palets sans trop les comprimer pour laisser des fissures qui permtteront un résultat plus croquants. Enfourner à 180°C pendant 25 min. Vérifier la cuisson, les retourner si le dessous est coloré sinon led mettre plus près de la résistance. Finir la cuisson en baissant à 160°C. 15 min. Laisser refroidir 15 min. Et les stocker dans une boite en verre ou aluminium.",
            "source": "CuistotDingo",
            "source_type": "Texte",
            "ingredients": [
                "noix de cajou",
                "noix",
                "noisette",
                "lait d'amande",
                "graine de tournesol",
                "graine de courge",
                "graine de chiah",
                "farine de kamut",
                "farine d'epeautre",
                "chocolat blanc",
                "amande"
            ],
            "astuces": "On peut les faire au chocolat noire avec des pépites de chocolat pour une version cookie.",
            "commentaire": "Biscuits très croustilant. Donne 12 biscuits environ.",
            "nombre de personne": "6 personnes",
            "type": "",
            "saison": "Recette pas de saison : noix,noisette"
        },
        "9": {
            "key": "9",
            "title": "Pâte à pizza",
            "description": "Le matin ou la veille, diviser la farine (500g) en 2 parts égales et mettre chaque moitié dans un saladier. Diviser l'eau (300g) en 2 parts. Celle qui recevra la levure devra avoir une température entre 35-38°C. Ajouter la levure (si sèche 3 g, si fraiche souvent en cube 9g) et remuer. Dans l'autre verre ajouter le sel (12.5g) et remuer. Dans l'un des saladier verser l'un des verre et mélanger rapidement pour avoir une pâte homogène. Idem pour l'autre saladier. Mélanger alors les deux pâtes ensemble et pétrir environ 5 minutes. La consistance doit être souple humide, non collante et douce au toucher. Recouvrir le saladier avec film et laisser reposer 10 min à T°ambiante puis la laisser reposer au frigo 10h à 24h. Deux heures avant cuisson, retirer la pâte du frigo et séparer les patons en 3 patons que l'on fera lever à température ambiante sous film. ",
            "source": "Philippe Schell",
            "source_type": "Texte",
            "ingredients": [
                "farine",
                "levure"
            ],
            "astuces": "Pour une pâte plus gourmande, on peut rajouter de l'huile d'olive",
            "commentaire": "Quantité pour 3 pizzas de taille normale. Par manque de temps, on peut sauter la séparation de la farine en 2 parts égales.",
            "nombre de personne": "3 personnes",
            "type": "",
            "saison": "Recette de saison"
        },
        "10": {
            "key": "10",
            "title": "Banana bread",
            "description": "Mélanger les ingrédients secs : 70g de farine complète, 50g de farine de sarrasin et 30g de maizena, 5g de levure, une pincée de canelle et de muscade. Mixer 40g de noisettes et 40g d'amandes et ajouter 2 oeufs, 60ml de lait d'avoine, 8g de beurre mou, 2 bananes. Mixer le tout et ajouter le sec et le sirop d'érable (3 c.a.s et l'extrait de vanille). Mixer. Mouler et ajouter une banane coupée en 2 face plane vers le haut. Enfourner à 180°C.",
            "source": "Marmiton",
            "source_type": "Texte",
            "ingredients": [
                "farine",
                "levure",
                "cannelle",
                "noix de muscade",
                "noisette",
                "amande",
                "oeuf",
                "lait",
                "beurre",
                "banane",
                "sirop erable",
                "vanille"
            ],
            "astuces": "La couleur du gâteau doit tirer vers le chocolat avec une farine de sarrasin, on peut aussi mettre plus de bananes sur le haut du gâteau.",
            "commentaire": "Testée et approuvée. Très bonne recette. Gâteau avec peu de sucre.",
            "nombre de personne": "3 personnes",
            "type": "",
            "saison": "Recette pas de saison : noisette"
        },
        "11": {
            "key": "11",
            "title": "Houmouss lisssse",
            "description": "Cuire les 250g de pois chiche à feu doux avec 1/2 c.a.c. de bicarbonate. Plonger les pois chiche dans l'eau froide pour les émonder. Dans un blender mixer les pois chiches avec 5 c.a.c de tahine, le jus d'un citron, deux gousses d'ail, une c.a.s d'huile d'olive, 60 ml de jus de pickles, sel. Une fois une consistance légèrement grumeleuse ajouter 4 à 5 glaçons et mixer encore 5 min.",
            "source": "Instagram Sophiethenutritionist",
            "source_type": "Texte",
            "ingredients": [
                "tahine",
                "pois chiche",
                "pickle",
                "citron",
                "bicarbonate",
                "ail"
            ],
            "astuces": "",
            "commentaire": "Testée et approuvée. La texture est vraiment lisse, même avec un blender bas de gamme.",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette pas de saison : ail"
        },
        "12": {
            "key": "12",
            "title": "Poireaux vinaigrette",
            "description": "Cuire à la vapeur des tronçons d'environ 3cm de blanc de poireaux. Dorer à la poêle les cacahuètes et les graines de sésame. Les mixer grossièrement. Laisser refroidir sur une assiette les poireaux. Préparer la vinaigrette 6 c.a.s. d'huile de sésame, 2 c.a.s de vinaigre de riz et 2 c.a.c de sause soja. Arroser de sauce vinaigrette. Saupoudrer de graines et de feuilles de coriandre hachée.",
            "source": "lacuisinecestsimple.com",
            "source_type": "Texte",
            "ingredients": [
                "poireau",
                "cacahuete",
                "graine de sesame",
                "huile de sesame",
                "vinaigre de riz",
                "sauce soja"
            ],
            "astuces": "Des poireaux jeunes et fins donneront un meilleur résultat.",
            "commentaire": "Testée et approuvée. Cette recette fait l'unanimité.",
            "nombre de personne": "",
            "type": "entrée",
            "saison": "Recette de saison"
        },
        "13": {
            "key": "13",
            "title": "Tofu mariné au vinaigre balsamique",
            "description": "Egoutter le tofu ferme (400g). Le découper en gros cubes. Préparer la marinade avec 3/8 cup de vinaigre balsamique, 3/8 cup d'huile d'olive, 3 c.a.s. de sauce tamari. 3 gousses d'ail en brunoise ou 1 c.a.s d'ail en poudre et 1 c.a.s. de sirop d'érable. Laisser mariné le tofu dans la vinaigrette pendant 14 a 48h en l'arrosant régulièrement. Peut etre consommé tel quel ou au four 30 min jusqu'à ce que le tofu soit brun. Saupoudrer de graines de sésame noir et de coriandre hachée.",
            "source": "Ali Francis",
            "source_type": "Texte",
            "ingredients": [
                "vinaigre balsamique",
                "tofu",
                "tamari",
                "sirop erable",
                "graine de sesame",
                "coriandre",
                "ail"
            ],
            "astuces": "On peut remplacer la sauce tamari par la sauce soja pour une version plus salée.",
            "commentaire": "Recette qui ira très bien dans une salade ou un sandwich. Un tofu de qualité, est prumordial. La recette originale préconise un tofu extra ferme mais un tofu semi ferme fera l'affaire.",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette pas de saison : ail"
        },
        "14": {
            "key": "14",
            "title": "Petit maqui sans riz",
            "description": "Dans un saladier, mélanger une boite de thon avec 1/2 c.a.s. de sauce soja, 1 c.a.s. de mayonnaise, 1/2 c.a.s. de sauce siracha, 1/2 c.a.s. d'huile de sésame, 1/2 c.a.c de poivre noir en poudre, 1 cup de céleri branche en fine lamelle (4mm), 3 petits oignons verts ou oignon nouveau, 1 cup de carottes râpées, 1 c.a.s. de graines de sésame, quelques algues de nori en morceaux. Bien mélanger, et rouler dans les feuilles de nori.",
            "source": "saltnpiipa instagram",
            "source_type": "Texte",
            "ingredients": [
                "thon",
                "sauce soja",
                "sauce siracha",
                "poivre noir",
                "oignon nouveau",
                "mayonnaise",
                "huile de sesame",
                "graine de sesame",
                "celeri branche",
                "carotte",
                "algue nori"
            ],
            "astuces": "",
            "commentaire": "Testée et aprouvée !",
            "nombre de personne": "2",
            "type": "",
            "saison": "Recette pas de saison : celeri branche"
        },
        "15": {
            "key": "15",
            "title": "Poulet à la crème curry",
            "description": "Dans un petit contenant en verre, ajouter les poitrines de poulet découpées en gros. Arroser de crème liquide 30% de manière à recouvrir et ajouter une c.a.s. de sauce soja, du curry, du chili en poudre, du poivre. Mettre au four 20 min à 180°C, sortir et découper les morceaux en plus petits (taille d\"une bouchée) et laisser cuire 15 min jusqu'à ce que la hauteur de la crème ait diminuée de moitié voir 3/4 et que le plat ait légèrement brunit sur les contours.",
            "source": "Muka et Xavier",
            "source_type": "Texte",
            "ingredients": [
                "sauce soja",
                "poulet",
                "poivre noir",
                "curry",
                "creme",
                "chili en poudre"
            ],
            "astuces": "",
            "commentaire": "Testée et approuvée",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette de saison"
        },
        "16": {
            "key": "16",
            "title": "salade estivale à la pastèque",
            "description": "Découper l'oignon en brunoise, la pastèque en mirepoix (cube de 1 cm), le concombre en jardinière (2 fois plus large que la julienne), les tomates cerises en 4, la menthe ciselée,la féta en macédoine (5-6 mm) et les olives en 4. Récupérer du jus de pastèque, mélanger le tout, assaisonner de poivre et arroser d'huile d'olive et de jus de citron (la féta étant déjà salée pas nécessaire de rajouter du sel).",
            "source": "Muka et Xavier",
            "source_type": "Texte",
            "ingredients": [
                "tomate cerise",
                "pasteque",
                "olive noire",
                "oignon rouge",
                "menthe",
                "feta",
                "concombre",
                "citron"
            ],
            "astuces": "L'eau de pastèque va rendre la salade encore plus fraiche et désaltérante.",
            "commentaire": "Testée et approuvée",
            "nombre de personne": "",
            "type": "entrée",
            "saison": "Recette pas de saison : concombre"
        },
        "17": {
            "key": "17",
            "title": "Fondant au chocolat version quebecoise",
            "description": "Préchauffer le four à 390F. Faire fondre 250g de chocolat noir mayrand à 70% de sucre au bain marie, baisser le feu et ajouter 150g de beurre doux pommade. Bien mélanger et verser le mélange qui doit etre liquide dans un saladier dans lequel on ajoute 100g de sucre blanc, 50g de cacao et 70g de farine blanche en mélangeant énergétiquement. L'appareil doit être fluide, si ce n'est pas le cas rajouter un peu d'eau, puis ajouter les 4 oeufs battus en omelette. On doit obtenir une texture fluide. Enfourner le gâteau à 300F 15 min. Le sortir et vérifier en faisant vibrer la gâteau que le centre est encore flasque. Si c'est le cas mettre le gâteau en position basse et mettre la fonction grill 3 à 5 min en surveillant bien, on souhaite former une croute au dessus.. Sortir le gateau et laisser le gâteau refroidir dans son moule 10 min et démouler. Vérifier le fondant, si le coeur coule c'est parfait.",
            "source": "Cuisto Dingo et Suzy Palatin",
            "source_type": "Texte",
            "ingredients": [
                "sucre",
                "oeuf",
                "farine",
                "chocolat",
                "cacao",
                "beurre"
            ],
            "astuces": "",
            "commentaire": "Testé et approuvé.",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette de saison"
        },
        "18": {
            "key": "18",
            "title": "Mi-quiche mi-pizza",
            "description": "Réaliser une pâte salée. Mettre 2-3 oignons à caraméliser avec un peu de sel sur feu moyen pendant 40 minutes. Dorer 3 poivrons découpés grossièrement en longueur à l'huile d'olive , sel, et une branche de thym. Quand ils colorent, ajouter le paprika. Sauter les champignons entiers, les colorer, les réserver et les découper en 3 ou 4 pour avoir de la mâche. Râper la tomate sans la peau et l'ajouter aux poivrons, cuire jusqu'à évaporation de l'eau. Battre trois oeufs et ajouter une bonne cuillère de moutarde de dijon, un filet de sauce soja, 1/2 c.a.c. d'ail haché ou râpé, les oignons caramélisés, les poivrons, un peu de mozzarella râpée et de la crème pour épaissir. L'appareil ne doit pas être trop liquide mais un peu visqueux. Décorer avec les poivrons et garnir de mozzarella. Enfourner 30 min à 180C.",
            "source": "Cuisto Dingo",
            "source_type": "Texte",
            "ingredients": [
                "tomate sechee",
                "tomate",
                "thym",
                "sauce soja",
                "poivron",
                "paprika",
                "oignon",
                "oeuf",
                "mozzarella",
                "moutarde",
                "farine",
                "creme",
                "champignon",
                "beurre",
                "ail"
            ],
            "astuces": "",
            "commentaire": "Testé et approuvé.",
            "nombre de personne": "6",
            "type": "plat",
            "saison": "Recette pas de saison : tomate,poivron,ail"
        },
        "19": {
            "key": "19",
            "title": "Potage de lentilles",
            "description": "Tremper les lentilles vertes dans l'eau 1h avant cuisson. Dans une cocotte ou un faitout, les nacrer avec une bonne quantité d'huile d'olive et deux pincée de gros sel pendant au moins 3 minutes. Mouiller en ajoutant trois fois le volume d'eau, une carotte détaillée en gros avec sa peau si bio, 3 gousses d'ail avec la peau légèrement écrasée, 4-5 graines de poivres (on cherche une diffusion lente du poivre donc préférable en grains plutôt qu'en poudre), 2 feuilles de laurier et 3 branches de céleri avec les feuilles. Laisser mijoter à feu doux 30-40 min, goûter la texture des lentilles, si tendre, stopper la cuisson et garder du jus pour faire comme une soupe de lentilles.",
            "source": "Cuistot Dingo",
            "source_type": "Texte",
            "ingredients": [
                "lentille",
                "celeri",
                "carotte",
                "ail"
            ],
            "astuces": "",
            "commentaire": "Testée et approuvée.",
            "nombre de personne": "",
            "type": "plat",
            "saison": "Recette pas de saison : ail"
        },
        "20": {
            "key": "20",
            "title": "Gâteau aux carottes",
            "description": "Mixer le sucre (380g dont 200g de brun) avec l'huile neutre (600g) et 8 oeufs au robot jusqu'à ce que ce soit homogène, réserver. Tamiser la farine (500g) avec le bicarbonate (4 c.a.c. pas plus), le sel (12g), les 5 épices (4 c.a.c), et mélanger au liquide. Râper les carottes (600g) manuellement ou au robot et concasser grossièrement les noix de pécan (200g). Mélanger le tout en ajoutant les raisins (150g) et mixer au robot une nouvelle fois pour obtenir une texture lisse homogène. Remplir les deux moules et enfourner 175C, à 50% d'humidité pendant 40-45 minutes.",
            "source": "Mateusz Ulman",
            "source_type": "Texte",
            "ingredients": [
                "farine",
                "oeuf",
                "sucre",
                "carotte",
                "cinq epice",
                "bicarbonate",
                "noix de pecan",
                "raisin"
            ],
            "astuces": "",
            "commentaire": "Testée et approuvée. Recette pour 2 moules.",
            "nombre de personne": "",
            "type": "dessert",
            "saison": "Recette pas de saison : raisin"
        },
        "21": {
            "key": "21",
            "title": "Salade de thon nori",
            "description": "Dans un saladier, ajouter une cup de carottes râpées, 1 cup de céleri émincés finement, 3 oignons nouveaux émincés, 1 boîte de thon entier, 3 c.a.s. de mayonnaise, 1 c.a.s. de sauce soja, 1 c.a.s. d'huile de sésame, 1 c.a.s. de graines de sésames grillées, 1/2 c.a.c. de poivre noir et une feuille de nori déchiquetée. Bien mélanger, se mange en l'enveloppant d'un peu d'algue de nori comme un maqui.",
            "source": "Salt&Pippa",
            "source_type": "Texte",
            "ingredients": [
                "carotte",
                "celeri branche",
                "thon",
                "sauce soja",
                "oignon nouveau",
                "mayonnaise",
                "huile de sesame",
                "graine de sesame",
                "algue nori"
            ],
            "astuces": "On peut ajouter une c.a.c. de sauce siracha. On peut remplacer les oignons nouveaux par des oignons rouges.",
            "commentaire": "Testée et approuvée.",
            "nombre de personne": "4",
            "type": "entree",
            "saison": "Recette pas de saison : celeri branche"
        },
        "22": {
            "key": "22",
            "title": "Salade de chou kale et haricot",
            "description": "Dans un saladier mélanger les moitiés de tomates cerises, les haricots rouges avec du sel, du poivre, ajouter le chou kale. Préparer une vinaigrette à base de vinaigre de riz, d'huile d'olive, un peu de moutarde de dijon et l'ajouter en mélangeant bien. Ajouter un peu de céleri branche émincé, du persil et coriandre hachés et des graines de chanvre.",
            "source": "Instagram",
            "source_type": "Texte",
            "ingredients": [
                "celeri branche",
                "moutarde",
                "chou kale",
                "haricot rouge",
                "tomate cerise",
                "graine de chanvre",
                "vinaigre de riz",
                "persil",
                "coriandre"
            ],
            "astuces": "Le chou kale doit être l'élément dominant. L'acidité du vinaigre s'associe bien avec le côté amer et terreux du chou kale.",
            "commentaire": "Testée et approuvée.",
            "nombre de personne": "4",
            "type": "entree",
            "saison": "Recette pas de saison : celeri branche"
        },
        "23": {
            "key": "23",
            "title": "Poisson aux tomates cerises",
            "description": "Emincer le blanc d'un gros poireau finement. Le faire fondre dans une poêle qui peut aller au four avec de l'huile d'olive et du sel. Une fois tendre, ajouter les tomates cerises, de préférence orange, car juteuses et sucrées. Quand les tomates commencent à éclater, les écraser pour libérer le jus. Ajouter une belle branche de basilic, l'écraser un peu dans la sauce, et touiller pour infuser les arômes. Ajouter le beurre (environ 100g), et un peu d'eau pour réaliser une belle sauce et laisser réduire 2-3 min. Déposer le filet de poisson blanc (tilapia, cabillaud etc.. ) sur la sauce et l'arroser. Enfourner 20-25 minutes à 150C. Rectifier l'assaisonnement en sel et poivre. ",
            "source": "Instagram",
            "source_type": "Texte",
            "ingredients": [
                "tomate cerise",
                "poisson",
                "poireau",
                "beurre",
                "basilic"
            ],
            "astuces": "On peut aussi ajouter l'un des éléments suivant, du pîment séché, du curcuma, des graines de fenouil, de l'ail. Le plat étant délicat, on en mettra en parcimonie. ",
            "commentaire": "Testée et approuvée.",
            "nombre de personne": "4",
            "type": "",
            "saison": "Recette de saison"
        },
        "24": {
            "key": "24",
            "title": "Tofu croustillant au miso brun",
            "description": "Faure chauffer une poêle à fond épais, pendant ce temps découper le tofu mi ferme en tranche de 5-6 mm d'épaisseur. Quand la poêle est chaude ajouter, pas mal d'huile d'olive, du gros sel, le tofu, baisser le feu. Le thym l'ajouter quand la poele est noins chaude pour ne pas le bruler et si possible en petite branche par dessus, cuire 10 à 20 min en bougeant le tofu et en l'arrosant de l'huile parfumée. Pour rechercher une belle coloration il faudra que l'huile ne soit pas en trop grande quantité. A mi cuisson ajouter une noisette de miso brun sur chaque tofu. L'huile doit être présente en petite quantité jusqu'à la fin et doit chanter pour une belle coloration.",
            "source": "CuistotDingo",
            "source_type": "Texte",
            "ingredients": [
                "tofu mi ferme",
                "thym",
                "miso brun"
            ],
            "astuces": "La clé de cette recette réside dans la patience, jusqu'à ce que le tofu soit bien coloré. La noix de miso doit avoir fondu légèrement tout en gardant une consistance. On peut tester yne version avec des graines de sarrasins ou sarrasins. Griller un seul côté donnera un jeu de texture entre le moelleu du dessus et le grillé du dessous.",
            "commentaire": "Testée et approuvée",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette de saison"
        },
        "25": {
            "key": "25",
            "title": "Muesli cacao",
            "description": "Dans un grand saladier bien mélanger 3 cups d'avoine, 3 cups de mélanges de graines, les amandes hachées, 1/3 cup  de cacao, 1 c.a.c de sel, 1/2 cup d'huile d\"olive ou neutre, 1/2 cup de sirop d'érable, 1/2 c.a.c de gingembre en poudre et idem de cannelle. Etaler sur une plaque de cuisson et enfourner 15 min à 160C. Retirer mélanger retourner et aplanir pour réenfourner 15 min. Une fois hors du four, laisser refroidir complètment pour obtenir le croustillant.",
            "source": "the_bareback_contessa_",
            "source_type": "Texte",
            "ingredients": [
                "sirop erable",
                "graine de tournesol",
                "graine de sesame",
                "graine de lin",
                "graine de courge",
                "graine de chiah",
                "gingembre",
                "flocon d'avoine",
                "cannelle",
                "cacao",
                "amande"
            ],
            "astuces": "",
            "commentaire": "Testée et approuvée",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette de saison"
        },
        "26": {
            "key": "26",
            "title": "Tarte tofu et mais",
            "description": "Réaliser la pâte en mettant dans un robot mixeur, 1/2 cup de farine de blé entier,1/2 cup de farine d'épeautre, 1/4 cup de farine de sarrasin, 1/2 cup de graine de courge, une c.a.c. de sel, 140g de beurre, 50g de cheddar, mixer et abaisser la pâte. Dans le meme mixeur, mixer 200g de tofu avec une bonne quantité de ciboulette, 3 c.a.c de levure maltée, 50g de cheddar. Rajouter un peu d'eau ou de lait ou de crème si besoin. Etaler l'appareil sur la pâte, ajouter les tomates en tranches, et coupées en 2 pour les tomates cerises, les grains de maïs si possible en paquet sinon détaché. Au four 20 min et 3 min en mode grill en surveillant, laisser dans le four chaud éteint pour finir la cuisson si besoin. Poser sur grille pour garder le croustillant de la pàte.",
            "source": "Insta",
            "source_type": "Texte",
            "ingredients": [
                "tomate cerise",
                "tomate",
                "tofu mi ferme",
                "nais en grain",
                "levure maltee",
                "graine de courge",
                "farrine de sarrasin",
                "farine d'epeautre",
                "farine",
                "ciboulette",
                "cheddar",
                "beurre"
            ],
            "astuces": "Dans la recette originale il y a de l'eau (70g) dans la pâte, le test sans eau donne de très bon résultats du moment que la pâte forme une boule.",
            "commentaire": "Testée et approuvée.",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette pas de saison : tomate"
        },
        "27": {
            "key": "27",
            "title": "Dessert banane coco",
            "description": "A l'aide d'un emporte pièce, disposer une premiere couche de banane tranchée pas trop épaisse, puis une couche de beurre d'amande, puis de pépite de chocolat mi sucrée ou noir, finir par une couche de banane avec des pepites et flocons de coco pour la déco. Enlever délicatement le moule, congeler 15 min pour que ça se tienne et enfourner jusqu-à ce que les pépites commencent à fondre. Sortir et déguster.",
            "source": "CuistotDingo",
            "source_type": "Texte",
            "ingredients": [
                "pate d'amande",
                "flocon de coco",
                "chocolat",
                "banane"
            ],
            "astuces": "On pourra laisser l'emporte piece dans la phase de congélation et de cuisson.",
            "commentaire": "Testée et approuvée !",
            "nombre de personne": "",
            "type": "dessert",
            "saison": "Recette de saison"
        },
        "28": {
            "key": "28",
            "title": "Samossa lentille corail champignon",
            "description": "Cuire les lentilles rouges a la vapeur avec dans l'eau des clous de girofle et feuilles de laurier. Bien remuer jusqu'à ce que les lentilles blanchissent. Cuire oignon rouge en brunoise à la poêle, quand translucide ajouter une couverture de champignons emincés grossierement, un peu d'eau si sec ou bouillon, et quelques minutes après, couvrir avec les lentilles (qui sont seches presque en purée), cuire 5 min et mettre une canne de coco, cumin, curcuma, sel. Base pour samossa. La pâte des samossa est simple, 250g de farine tamisée avec 400g d'eau, un peu de sel et d'huile d'olive. Bien mélanger. Au bain marie avec pinceau tracer les feuilles de brique d'un geste rapide et assuré. Laisser cuire 2 3 min et décoller. Garnir les samossas  en rouleaux ou triangle et les frire.",
            "source": "",
            "source_type": "Texte",
            "ingredients": [
                "oignon rouge",
                "lentille corail",
                "laurier",
                "lait de coco",
                "farine",
                "curcuma",
                "cumin",
                "clou de girofle",
                "champignon"
            ],
            "astuces": "",
            "commentaire": "",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette de saison"
        },
        "29": {
            "key": "29",
            "title": "Ratatouille",
            "description": "Découper les 4 oignons en lamelles et les faire blondir dans une cocotte dans une quantité d’huile modeste. Bien attendre qu’il blondisse et qu’ils rendent leur eau (feu doux 5-6 min). Couper 3 courgettes non épluchées (sauf si courgettes âgées plus amer) en rondelle et les ajouter aux oignons, couvrir et monter le feu 2 min.\nLaisser la cocotte à découvert et touiller pour que l’eau des légumes s’évapore. Couper l’aubergine avec la peau en petit cube, et les mettre uniquement quand le liquide des courgettes est parti, fermer la cocotte et monter le feu.  Ouvrir la cocotte et laisser à nouveau le liquide s’évaporer, touiller. Ajouter le bouquet de thym, de romarin, 2 feuilles de laurier, poivre, sel et l’ail haché (4 gousses d'ail au dernier moment pour qu’il soit présent au goût). Fermer la cocotte, et laisser infuser les aromates, touiller délicatement pour laisser les bouquets intacts. Ajouter les dés de tomates (5 à 6 tomates), préalablement émondées, et fermer la cocotte, laisser une ambiance humide quelques minutes. Ouvrir et laisser s’évaporer en touillant bien. Quand la texture devient une mixture, enlever les aromates. En option on peut à ce stade ajouter deux œufs mais perso je prefere sans.",
            "source": "Jean-Claude Malgoire",
            "source_type": "Texte",
            "ingredients": [
                "tomate",
                "thym",
                "romarin",
                "oignon",
                "laurier",
                "courgette",
                "aubergine",
                "ail"
            ],
            "astuces": "Le secret d’une bonne ratatouille réside dans le fait de patiemment attendre que chaque légume perde son eau et de touiller continuellement.",
            "commentaire": "",
            "nombre de personne": "",
            "type": "",
            "saison": "Recette pas de saison : tomate,courgette,aubergine,ail"
        },
    }
}
