mydico_frigo = {
    "code": "jjdHpajappalmnrkrmiapksmcmcaenpnajkDDno56456wv466V6a6e8vYY46aRV6Arv6reth6h46shOP4s6h4a68",
    "ingredients": {
        "cannelle": "ingredient",
        "carotte": "ingredient",
        "chou chinois": "ingredient",
        "citron": "ingredient",
        "concombre": "ingredient",
        "courgette": "ingredient",
        "cumin": "ingredient",
        "curcuma": "ingredient",
        "fecule de mais": "ingredient",
        "fromage": "ingredient",
        "graine de chiah": "ingredient",
        "graine de courge": "ingredient",
        "graine de lin": "ingredient",
        "graine de sesame": "ingredient",
        "haricot rouge": "ingredient",
        "haricot vert": "ingredient",
        "pate d'amande": "ingredient",
        "lentille corail": "ingredient",
        "mayonnaise": "ingredient",
        "melon": "ingredient",
        "miso": "ingredient",
        "moutarde": "ingredient",
        "oeuf": "ingredient",
        "oignon": "ingredient",
        "oignon nouveau": "ingredient",
        "paprika": "ingredient",
        "patate douce": "ingredient",
        "pate": "ingredient",
        "poivre noir": "ingredient",
        "poivron": "ingredient",
        "pomme": "ingredient",
        "quinoa": "ingredient",
        "raisin noir": "ingredient",
        "riz": "ingredient",
        "sauce soja": "ingredient",
        "sucre": "ingredient",
        "sucre glace": "ingredient",
        "thon": "ingredient",
        "tomate": "ingredient",
        "yaourt": "ingredient",
        "beurre": "ingredient",
        "cacahuete": "ingredient",
        "coco": "ingredient",
        "cacao": "ingredient",
        "farine": "ingredient",
        "levure": "ingredient",
        "chocolat": "ingredient",
        "persil": "ingredient",
        "lait de coco": "ingredient",
        "haricot oeil noir": "ingredient",
        "tahine": "ingredient",
        "pois chiche": "ingredient",
        "poireau": "ingredient",
        "huile de sesame": "ingredient",
        "vinaigre de riz": "ingredient",
        "tofu": "ingredient",
        "vinaigre balsamique": "ingredient",
        "sirop erable": "ingredient",
        "tamari": "ingredient",
        "coriandre": "ingredient",
        "ail": "ingredient",
        "tofu mi ferme": "ingredient",
        "thym": "ingredient",
        "tomate cerise": "ingredient",
        "poisson": "ingredient"
    }
}
