ScreenSeason:
    id: _screen_season
    name: "screen season"

    #MDBoxLayout:
    MyScatterPlane:
        id: _scatter
        #pos_hint: {'center_x': .5, 'center_y': .5}
        do_rotation: False

        Image:
            id: _season_image_pc
            source: app.source_season_pc
            fit_mode : "fill"
            size: _screen_season.width , _screen_season.height

    MDIconButton:
        icon: "arrow-left"
        md_bg_color: 1, 1, 1, .6
        x: 12
        pos_hint: {"top": .99}
        on_release:
            app.manager.restore_screen()
            app.manager.current = "screen D1"